# Generated by Django 2.2.19 on 2021-04-25 23:06
# Generated by Django 2.2.19 on 2021-04-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorites', to='boards.Board')),
            ],
        ),
    ]
